# -*- coding: utf-8 -*-
"""Majaorproject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R52ZEMBNtRDt_AUXDONYF5ad2UAOqUd6
"""

import pandas as pd
df=pd.read_csv('https://raw.githubusercontent.com/ameenmanna8824/DATASETS/main/Social_Network_Ads.csv')
df

df.shape

df.size

df.info()

x=df.iloc[:,2:4].values
x

y=df.iloc[:,4].values
y

df['Purchased'].value_counts()

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, random_state = 0)

print(x.shape)
print(x_train.shape)
print(x_test.shape)

print(y.shape)
print(y_train.shape)
print(y_test.shape)

from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(x_train,y_train)

y_pred=model.predict(x_test)
y_pred

y_test

from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)*100

a=scaler.transform([[25,5000]])
a

model.predict(a)

b=scaler.transform([[50,50000]])
b

model.predict(b)